local-url: registry.sulamerica.br:4000
images:
  jboss-eap-6/eap64-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-eap-7/eap70-openshift:
    remote-url: registry.access.redhat.com
    version: 1 
  openshift3/image-inspector:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/jenkins-1-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/jenkins-2-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/jenkins-slave-base-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/jenkins-slave-maven-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/jenkins-slave-nodejs-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/logging-auth-proxy:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/logging-curator:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/logging-deployer:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/logging-elasticsearch:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/logging-kibana:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/logging-fluentd:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/metrics-cassandra:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/metrics-deployer:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/metrics-hawkular-metrics:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/metrics-heapster:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/oauth-proxy:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-ansible:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-deployer:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-docker-builder:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-docker-registry:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-haproxy-router:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-logging-auth-proxy:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-logging-curator:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-logging-deployer:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-logging-elasticsearch:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-logging-fluentd:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-logging-kibana:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-metrics-deployer:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-metrics-hawkular-metrics:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-metrics-hawkular-openshift-agent:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-metrics-heapster:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-pod:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-sti-builder:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/registry-console:
    remote-url: registry.access.redhat.com
    version: 1
  redhat-openjdk-18/openjdk18-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  redhat-sso-7/sso70-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/httpd-24-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/mariadb-100-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/mariadb-101-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/mongodb-26-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/mongodb-32-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/mysql-56-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/mysql-57-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/nginx-110-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/nginx-18-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/nodejs-4-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/perl-520-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/perl-524-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/php-56-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/php-70-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/postgresql-94-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/postgresql-95-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/python-27-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/python-34-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/python-35-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/redis-32-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/ruby-22-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/ruby-23-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/ruby-24-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/s2i-base-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/s2i-core-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  dotnet/dotnetcore-10-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  dotnet/dotnetcore-11-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  dotnet/dotnet-20-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  dotnet/dotnet-20-runtime-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-fuse-6/fis-java-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-fuse-6/fis-karaf-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-amq-6/amq62-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-amq-6/amq63-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-datagrid-6/datagrid65-client-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-datagrid-6/datagrid65-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-datagrid-7/datagrid71-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-datagrid-7/datagrid71-client-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-datavirt-6/datavirt63-driver-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-datavirt-6/datavirt63-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-decisionserver-6/decisionserver62-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-decisionserver-6/decisionserver63-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-decisionserver-6/decisionserver64-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-eap-7-tech-preview/eap71-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-processserver-6/processserver63-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-processserver-6/processserver64-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-webserver-3/webserver30-tomcat7-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-webserver-3/webserver30-tomcat8-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-webserver-3/webserver31-tomcat7-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  jboss-webserver-3/webserver31-tomcat8-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  redhat-sso-7/sso71-openshift:
    remote-url: registry.access.redhat.com
    version: 1
  rhgs3/rhgs-volmanager-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhgs3/rhgs-server-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-service-catalog:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ruby-20-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  heketi/heketi:
    remote-url: docker.io
    version: 2
  rhgs3/rhgs-gluster-block-prov-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/mongodb-24-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/mysql-55-rhel7:
    remote-url: registry.access.redhat.com   
    version: 1
  openshift3/nodejs-010-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhscl/nodejs-6-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/perl-516-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/php-55-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/postgresql-92-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/python-33-rhel7:
    remote-url: registry.access.redhat.com
    version: 1
  rhel7/etcd:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-ansible-service-broker:
    remote-url: registry.access.redhat.com
    version: 1
  openshift3/ose-recycler:
    remote-url: registry.access.redhat.com
    version: 1
